ClaimTool: "APPLE"
RectangleClaimTool: "GOLDEN_HOE"

PolyName:
  Join:
    message:
      - join text1
      - join text2
      - join text3
    delay: 0.5
  Leave:
    message:
      - leave text1
      - leave text2
      - leave text3
    delay: 1